name: diagnyx-services

services:
  # IMPORTANT: NO databases, caches, or infrastructure services here!
  # Use ONLY shared services from docker:
  # - database-postgres (host.docker.internal:5433)
  # - cache-redis (host.docker.internal:6380)

  # User Service
  user-service:
    build:
      context: ../../user-service
      dockerfile: Dockerfile
    container_name: diagnyx-user-service
    ports:
      - "8001:8001"
    env_file:
      - ../../user-service/.env
    networks:
      - diagnyx-workspace
      - shared-infra-services

  # AI Quality Service
  ai-quality-service:
    build:
      context: ../../ai-quality-service
      dockerfile: Dockerfile
    container_name: diagnyx-ai-quality-service
    ports:
      - "8002:8002"
    env_file:
      - ../../ai-quality-service/.env
    networks:
      - diagnyx-workspace
      - shared-infra-services

  # Observability Service (Go)
  observability-service:
    build:
      context: ../../observability-service
      dockerfile: Dockerfile
    container_name: diagnyx-observability-service
    ports:
      - "8080:8080"
    env_file:
      - ../../observability-service/.env
    networks:
      - diagnyx-workspace
      - shared-infra-services

  # Optimization Service (Go)
  optimization-service:
    build:
      context: ../../optimization-service
      dockerfile: Dockerfile
    container_name: diagnyx-optimization-service
    ports:
      - "8003:8003"
    env_file:
      - ../../optimization-service/.env
    networks:
      - diagnyx-workspace
      - shared-infra-services

  # API Gateway (Node.js/Express)
  diagnyx-api-gateway:
    build:
      context: ../../diagnyx-api-gateway
      dockerfile: Dockerfile
    container_name: diagnyx-api-gateway
    ports:
      - "8443:8080"  # Maps external 8443 to internal 8080
    env_file:
      - ../../diagnyx-api-gateway/.env
    depends_on:
      - user-service
      - observability-service
      - ai-quality-service
      - optimization-service
    networks:
      - diagnyx-workspace
      - shared-infra-services

  # Diagnyx UI (Marketing Website)
  diagnyx-ui:
    build:
      context: ../../diagnyx-ui
      dockerfile: Dockerfile
    container_name: diagnyx-ui
    ports:
      - "3002:3002"
    env_file:
      - ../../diagnyx-ui/.env
    networks:
      - diagnyx-workspace
      - shared-infra-services

  # Dashboard Service (Main Dashboard)
  dashboard-service:
    build:
      context: ../../dashboard-service
      dockerfile: Dockerfile
    container_name: diagnyx-dashboard-service
    ports:
      - "3000:3000"
    env_file:
      - ../../dashboard-service/.env
    depends_on:
      - diagnyx-api-gateway
    networks:
      - diagnyx-workspace
      - shared-infra-services

  # Note: Monitoring infrastructure is now provided by shared containers:
  # - monitoring-prometheus on localhost:9091
  # - monitoring-grafana on localhost:3006
  # - observability-otel on localhost:4319 (gRPC), 4320 (HTTP), 8889 (metrics)

volumes: {}

networks:
  diagnyx-workspace:
    name: diagnyx-services
    driver: bridge
  shared-infra-services:
    external: true
    name: shared-infra-services