name: diagnyx-services

services:
  # Note: PostgreSQL and Redis are now provided by shared infrastructure containers:
  # - database-postgres on localhost:5433
  # - cache-redis on localhost:6380

  # Note: Kafka, Zookeeper, and Elasticsearch are now provided by shared infrastructure:
  # - messaging-kafka on localhost:9093
  # - messaging-zookeeper on localhost:2182 
  # - search-elasticsearch on localhost:9201

  # User Service
  user-service:
    build:
      context: ../../user-service
      dockerfile: Dockerfile
    container_name: diagnyx-user-service
    ports:
      - "8001:8001"
    environment:
      SPRING_PROFILES_ACTIVE: development
      DATABASE_URL: postgres://shared_user:shared_pass123@database-postgres:5432/shared_db
      REDIS_URL: redis://cache-redis:6379
      JWT_SECRET: dev-jwt-secret
    networks:
      - diagnyx-workspace
      - shared-infra-services

  # AI Quality Service
  ai-quality-service:
    build:
      context: ../../ai-quality-service
      dockerfile: Dockerfile
    container_name: diagnyx-ai-quality
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      ENVIRONMENT: development
      DATABASE_URL: postgres://shared_user:shared_pass123@database-postgres:5432/shared_db
      REDIS_URL: redis://cache-redis:6379
    networks:
      - diagnyx-workspace
      - shared-infra-services

  # Observability Service (Go)
  observability-service:
    build:
      context: ../../observability-service
      dockerfile: Dockerfile
    container_name: diagnyx-observability
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      ENVIRONMENT: development
      DATABASE_URL: postgres://shared_user:shared_pass123@database-postgres:5432/shared_db
      REDIS_URL: redis://cache-redis:6379
      KAFKA_BROKER_URL: messaging-kafka:29092
      ELASTICSEARCH_URL: http://search-elasticsearch:9200
    networks:
      - diagnyx-workspace
      - shared-infra-services

  # Optimization Service (Go)
  optimization-service:
    build:
      context: ../../optimization-service
      dockerfile: Dockerfile
    container_name: diagnyx-optimization
    ports:
      - "8003:8003"
    environment:
      PORT: 8003
      ENVIRONMENT: development
      DATABASE_URL: postgres://shared_user:shared_pass123@database-postgres:5432/shared_db
      REDIS_URL: redis://cache-redis:6379
    networks:
      - diagnyx-workspace
      - shared-infra-services

  # API Gateway (Node.js/Express)
  api-gateway:
    build:
      context: ../../diagnyx-api-gateway
      dockerfile: Dockerfile
    container_name: diagnyx-api-gateway
    ports:
      - "8000:8080"
    environment:
      PORT: 8080
      ENVIRONMENT: development
      USER_SERVICE_URL: http://diagnyx-user-service:8001
      OBSERVABILITY_SERVICE_URL: http://diagnyx-observability:8080
      AI_QUALITY_SERVICE_URL: http://diagnyx-ai-quality:8002
      OPTIMIZATION_SERVICE_URL: http://diagnyx-optimization:8003
      REDIS_URL: redis://cache-redis:6379
    networks:
      - diagnyx-workspace
      - shared-infra-services

  # Diagnyx UI (Unified Website and Dashboard)
  diagnyx-ui:
    build:
      context: ../../diagnyx-ui
      dockerfile: Dockerfile
    container_name: diagnyx-ui
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080
      NEXT_PUBLIC_AUTH_URL: http://localhost:3001
      NEXT_PUBLIC_ENVIRONMENT: development
    networks:
      - diagnyx-workspace
      - shared-infra-services

  # Note: Monitoring infrastructure is now provided by shared containers:
  # - monitoring-prometheus on localhost:9091
  # - monitoring-grafana on localhost:3006
  # - observability-otel on localhost:4319 (gRPC), 4320 (HTTP), 8889 (metrics)

volumes: {}

networks:
  diagnyx-workspace:
    name: diagnyx-services
    driver: bridge
  shared-infra-services:
    external: true