global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'diagnyx-services'
    static_configs:
      - targets: 
          - 'diagnyx-ui:3000'
          - 'diagnyx-user-service:8001'
          - 'diagnyx-ai-quality:8002'

  - job_name: 'infrastructure'
    static_configs:
      - targets:
          - 'postgres:5432'
          - 'redis:6379'
          - 'elasticsearch:9200'
          - 'kafka:9092'

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']