apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: diagnyx
  labels:
    app: api-gateway
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        version: v1
    spec:
      containers:
      - name: api-gateway
        image: diagnyx/diagnyx-api-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: https
        env:
        - name: PORT
          value: "8443"
        - name: NODE_ENV
          value: "production"
        - name: USER_SERVICE_URL
          value: "http://user-service.diagnyx.svc.cluster.local:8080"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: diagnyx-secrets
              key: JWT_SECRET
        - name: HTTPS_ENABLED
          value: "true"
        - name: RATE_LIMIT_WINDOW_MS
          value: "60000"
        - name: RATE_LIMIT_MAX_REQUESTS
          value: "100"
        - name: ALLOWED_ORIGINS
          value: "https://app.diagnyx.ai,https://diagnyx.ai"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: diagnyx
  labels:
    app: api-gateway
spec:
  type: ClusterIP
  ports:
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: api-gateway