apiVersion: v1
kind: ConfigMap
metadata:
  name: diagnyx-config
  namespace: diagnyx
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "info"
  OTLP_ENDPOINT: "otel-collector.diagnyx.svc.cluster.local:4317"
  KAFKA_BROKERS: "kafka-0.kafka-headless.diagnyx.svc.cluster.local:9092,kafka-1.kafka-headless.diagnyx.svc.cluster.local:9092,kafka-2.kafka-headless.diagnyx.svc.cluster.local:9092"
  KAFKA_TOPIC: "llm-traces"
  REDIS_URL: "redis://redis-master.diagnyx.svc.cluster.local:6379"
  API_GATEWAY_URL: "http://api-gateway.diagnyx.svc.cluster.local:8080"
---
apiVersion: v1
kind: Secret
metadata:
  name: diagnyx-secrets
  namespace: diagnyx
type: Opaque
stringData:
  DATABASE_URL: "postgres://diagnyx:password@postgres.diagnyx.svc.cluster.local:5432/diagnyx?sslmode=require"
  JWT_SECRET: "your-jwt-secret-key-change-this-in-production"
  JWT_REFRESH_SECRET: "your-refresh-secret-key-change-this-in-production"
  OPENAI_API_KEY: "sk-proj-xxxxxxxxxxxxx"
  ANTHROPIC_API_KEY: "sk-ant-xxxxxxxxxxxxx"
  STRIPE_API_KEY: "sk_live_xxxxxxxxxxxxx"
  SENDGRID_API_KEY: "SG.xxxxxxxxxxxxx"